#!/usr/bin/env bash
# director#4 verification. Proves the authorization block (authorization.conf)
# binds a credential to the subjects it may use, WITHOUT touching the live probe
# broker on :4222 or its JetStream store.
#
# It stands up a throwaway broker on :4223 with its own temp store, bootstraps
# the same streams and presence KV as the operator, then asserts:
#   1. an anonymous connection is refused (the defect: open ">" is closed);
#   2. the ops credential can publish and subscribe inside agent.aae-orc.ops.>;
#   3. the ops credential can write and read the presence KV (the JS/KV it needs);
#   4. the ops credential is REFUSED on another team's subtree
#      (agent.aae-orc.secops.>), which is the credential-to-subject binding.
#
# Everything is confined to a temp dir and :4223, torn down on exit. Reversible:
# kill the process, remove the temp dir. Neither exists after this script ends.
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
AUTHZ="$HERE/authorization.conf"
PORT=4223
MON=8223
URL="nats://127.0.0.1:${PORT}"

test -f "$AUTHZ" || { echo "authorization.conf not found beside this script"; exit 1; }
command -v nats-server >/dev/null || { echo "nats-server not on PATH"; exit 1; }
command -v nats >/dev/null || { echo "nats CLI not on PATH"; exit 1; }

# Refuse to run if :4223 is already taken; never risk the live :4222.
if lsof -iTCP:${PORT} -sTCP:LISTEN -n -P >/dev/null 2>&1; then
  echo "port ${PORT} is in use; refusing to run so nothing live is disturbed"; exit 1
fi

WORK="$(mktemp -d)"
export XDG_CONFIG_HOME="$WORK/xdg"   # keep any user nats context out of this run
mkdir -p "$XDG_CONFIG_HOME"
# Throwaway credentials, this run only. Not secrets, never reused, never live.
export DIRECTOR_ADMIN_PASS="verify-admin-$$-$RANDOM"
export DIRECTOR_OPS_PASS="verify-ops-$$-$RANDOM"

CONF="$WORK/nats-verify.conf"
cat > "$CONF" <<EOF
# Generated by verify-auth.sh. Throwaway broker on :${PORT}, temp store.
host: "127.0.0.1"
port: ${PORT}
http_port: ${MON}
server_name: director-phase0-verify
jetstream {
  store_dir: "$WORK/store"
  max_memory_store: 268435456
  max_file_store: 1073741824
}
EOF
# Single-source the authorization block: append the repo's file verbatim.
cat "$AUTHZ" >> "$CONF"

SRV_PID=""
cleanup() {
  [ -n "$SRV_PID" ] && kill "$SRV_PID" 2>/dev/null
  wait "$SRV_PID" 2>/dev/null
  rm -rf "$WORK"
}
trap cleanup EXIT

# Config must parse (this also validates authorization.conf).
if ! nats-server -t -c "$CONF" >"$WORK/cfgtest.log" 2>&1; then
  echo "FAIL: config did not validate"; cat "$WORK/cfgtest.log"; exit 1
fi

nats-server -c "$CONF" >"$WORK/server.log" 2>&1 &
SRV_PID=$!

# Wait for readiness on the monitor port (no auth needed there).
ready=0
for _ in $(seq 1 50); do
  if curl -fs "http://127.0.0.1:${MON}/healthz" >/dev/null 2>&1; then ready=1; break; fi
  sleep 0.1
done
[ "$ready" = 1 ] || { echo "FAIL: broker did not come up on :${PORT}"; cat "$WORK/server.log"; exit 1; }

admin() { nats --server "$URL" --user director_admin --password "$DIRECTOR_ADMIN_PASS" "$@"; }
ops()   { nats --server "$URL" --user ops           --password "$DIRECTOR_OPS_PASS"   "$@"; }
anon()  { nats --server "$URL" "$@"; }

# Bootstrap the same streams and KV the probe uses, as the operator.
admin stream add AGENT_INBOX \
  --subjects 'agent.*.*.*.inbox,agent.*.*.role.*.inbox' \
  --storage file --retention limits --max-age 24h --max-msg-size 65536 \
  --dupe-window 2m --defaults >/dev/null 2>&1
admin stream add AGENT_AUDIT \
  --subjects 'agent.audit' --storage file --retention limits --max-age 720h \
  --defaults >/dev/null 2>&1
admin kv add AGENT_STATE --ttl 90s --storage file >/dev/null 2>&1

pass=0; fail=0
ok()   { echo "  PASS: $1"; pass=$((pass+1)); }
bad()  { echo "  FAIL: $1"; fail=$((fail+1)); }

echo "== director#4 broker authorization, :${PORT} =="

# 1. The defect: an anonymous client must be refused (no open ">").
if anon pub agent.aae-orc.ops.planner.inbox hi >/dev/null 2>&1; then
  bad "anonymous publish was accepted (open '>' NOT closed)"
else
  ok "anonymous publish refused (open '>' closed)"
fi

# 2a. ops publishes inside its own team subtree.
if ops pub agent.aae-orc.ops.planner.inbox 'hello from ops' >/dev/null 2>&1; then
  ok "ops publish to agent.aae-orc.ops.planner.inbox accepted"
else
  bad "ops publish to its own team inbox was refused"
fi

# 2b. ops subscribes inside its own subtree and receives its own publish.
ops sub 'agent.aae-orc.ops.planner.inbox' --count 1 >"$WORK/sub.out" 2>&1 &
subpid=$!
sleep 0.5
ops pub agent.aae-orc.ops.planner.inbox 'roundtrip' >/dev/null 2>&1
wait "$subpid" 2>/dev/null
if grep -q 'roundtrip' "$WORK/sub.out"; then
  ok "ops subscribe within agent.aae-orc.ops.> delivered the message"
else
  bad "ops subscribe within its subtree did not deliver"; sed 's/^/    /' "$WORK/sub.out"
fi

# 2c. ops uses the team broadcast (inside its subtree).
if ops pub agent.aae-orc.ops.broadcast 'team ping' >/dev/null 2>&1; then
  ok "ops publish to the team broadcast accepted"
else
  bad "ops publish to its team broadcast was refused"
fi

# 3. ops writes and reads the presence KV (the JS/KV it needs).
if ops kv put AGENT_STATE presence.ops.planner.zzz '{"state":"idle"}' >/dev/null 2>&1 \
   && ops kv get AGENT_STATE presence.ops.planner.zzz --raw 2>/dev/null | grep -q 'idle'; then
  ok "ops can write and read the presence KV"
else
  bad "ops could not use the presence KV"
fi

# 4a. Confinement: ops must NOT publish into another team's subtree.
if ops pub agent.aae-orc.secops.evil.inbox 'pwn' >/dev/null 2>&1; then
  bad "ops published into agent.aae-orc.secops.> (confinement BROKEN)"
else
  ok "ops refused publishing into agent.aae-orc.secops.> (confinement holds)"
fi

# 4b. Confinement: ops must NOT subscribe to another team's subtree.
timeout 3 ops sub 'agent.aae-orc.secops.>' --count 1 >"$WORK/deny.out" 2>&1 || true
if grep -qi 'violation\|not authorized\|permission' "$WORK/deny.out"; then
  ok "ops refused subscribing to agent.aae-orc.secops.> (permissions violation)"
elif [ ! -s "$WORK/deny.out" ] || ! grep -q 'roundtrip\|Received' "$WORK/deny.out"; then
  ok "ops subscribe to agent.aae-orc.secops.> delivered nothing (denied, no leak)"
else
  bad "ops subscribe to another team's subtree was allowed"; sed 's/^/    /' "$WORK/deny.out"
fi

echo "== result: ${pass} passed, ${fail} failed =="
[ "$fail" -eq 0 ]
